#=========================================
# BusyBox/Bash-only targets
#
# Tests performed on targets without git or
# HTTPS-enabled curl/wget. These are relevant
# tests for basic language checks against
# supported Bash versions.
#
# Tests:
# - YAML processing
# - Space install
#
#=========================================
bash32_base_tests:
  image: bash:3.2
  script:
    - which bash
    - bash --version
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh

bash40_base_tests:
  image: bash:4.0
  script:
    - which bash
    - bash --version
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh

bash44_base_tests:
  image: bash:4.4
  script:
    - which bash
    - bash --version
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh

bashlatest_base_tests:
  image: bash:latest
  script:
    - which bash
    - bash --version
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh

#=========================================
# Full tests
#
#=========================================
alpine_test_all:
  image: alpine:latest
  script:
    - apk add --update bash curl git
    - mkdir ~/.ssh
    - printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
    - which bash
    - which busybox
    - bash --version
    - bash test/test_all_exit_status.sh
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh

arch_test_all:
  image: finalduty/archlinux:latest
  script:
    - pacman -Sy --noconfirm curl git
    - mkdir ~/.ssh
    - printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
    - which bash
    - bash --version
    - bash test/test_all_exit_status.sh
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh

centos_test_all:
  image: centos:latest
  script:
    - yum -y update && yum -y install curl git which
    - mkdir ~/.ssh
    - printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
    - which bash
    - bash --version
    - bash test/test_all_exit_status.sh
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh

debianjessie_test_all:
  image: debian:jessie
  script:
    - apt-get update -qq && apt-get install -y -qq curl git
    - mkdir ~/.ssh
    - printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
    - which bash
    - bash test/test_all_exit_status.sh
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh

debianjessie_curl_test_all:
  image: debian:jessie
  script:
    - apt-get update -qq && apt-get install -y -qq curl
    - mkdir ~/.ssh
    - printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
    - which bash
    - bash test/test_all_exit_status.sh
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh

debianjessie_wget_test_all:
  image: debian:jessie
  script:
    - apt-get update -qq && apt-get install -y -qq wget
    - mkdir ~/.ssh
    - printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
    - which bash
    - bash test/test_all_exit_status.sh
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh

debianlatest_test_all:
  image: debian:latest
  script:
    - apt-get update -qq && apt-get install -y -qq curl git
    - mkdir ~/.ssh
    - printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
    - which bash
    - bash test/test_all_exit_status.sh
    - bash test/test_install.sh
    - bash test/test_core.sh
    - bash test/test_function.sh
    - bash test/test_yaml.sh


