#
# YAML-only basic tests for multiple boxes
#

alpinelatest_test_yaml:
  image: alpine:latest
  script:
    - apk add --update bash
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bash32_test_yaml:
  image: bash:3.2
  script:
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bash40_test_yaml:
  image: bash:4.0
  script:
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bash44_test_yaml:
  image: bash:4.4
  script:
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bashlatest_test_yaml:
  image: bash:latest
  script:
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

busybox_test_yaml:
  image: progrium/busybox
  script:
    - opkg-install bash
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

debianlatest_test_yaml:
  image: debian:latest
  script:
    - which bash
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

#
# Run exit status code checking for Space
#

debianjessie_test_yaml:
  image: debian:jessie
  script:
    - apt-get update -qq && apt-get install -y -qq curl git
    - mkdir ~/.ssh
    - printf "Host *\n StrictHostKeyChecking no" > ~/.ssh/config
    - which bash
    - bash test/test_all_exit_status.sh

