before_script:
  - which bash
  - bash --version

debianjessie_test_yaml:
  image: debian:jessie
  script:
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

debianlatest_test_yaml:
  image: debian:latest
  script:
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

busyboxg_test_yaml:
  image: busybox:glibc
  script:
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

busyboxm_test_yaml:
  image: busybox:musl
  script:
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

busyboxu_test_yaml:
  image: busybox:uclibc
  script:
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bash30_test_yaml:
  image: bash:3.0
  script:
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bash44_test_yaml:
  image: bash:4.4
  script:
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bashlatest_test_yaml:
  image: bash:latest
  script:
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

