alpinelatest_test_yaml:
  image: alpine:latest
  script:
    - apk add --update bash
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bash32_test_yaml:
  image: bash:3.2
  script:
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bash40_test_yaml:
  image: bash:4.0
  script:
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bash44_test_yaml:
  image: bash:4.4
  script:
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

bashlatest_test_yaml:
  image: bash:latest
  script:
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

busyboxg_test_yaml:
  image: busybox:glibc
  script:
    - opkg-install bash
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

busyboxm_test_yaml:
  image: busybox:musl
  script:
    - opkg-install bash
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

busyboxu_test_yaml:
  image: busybox:uclibc
  script:
    - opkg-install bash
    - which bash
    - bash --version
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

debianjessie_test_yaml:
  image: debian:jessie
  script:
    - which bash
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a

debianlatest_test_yaml:
  image: debian:latest
  script:
    - which bash
    - bash space -f ./test/yaml/test.yaml /tests/0/ -a


